// lib/templates/baseTemplates.ts

import { Template } from "@/lib/types/template";
import { colorSchemes } from "./colorSchemes";

export const baseTemplates: Template[] = [
  {
    id: 'professional-traditional',
    name: 'Professional Traditional',
    description: 'Clean and traditional design perfect for corporate roles',
    category: 'business',
    style: 'professional',
    thumbnail: '/templates/thumbnails/professional-traditional.png',
    previewImages: ['/templates/previews/professional-traditional.png'],
    config: {
      layout: {
        type: 'single-column',
        headerStyle: 'centered',
        columns: 1,
        showIcons: false,
        showDividers: true,
        compactMode: false,
      },
      typography: {
        fontFamily: 'georgia',
        headingFont: 'georgia',
        bodyFont: 'georgia',
        sizes: {
          name: 24,
          heading: 14,
          subheading: 12,
          body: 10,
          small: 9,
        },
        weights: {
          normal: 400,
          medium: 500,
          semibold: 600,
          bold: 700,
        },
      },
      colors: colorSchemes.professionalBlue,
      spacing: {
        sectionGap: 16,
        itemGap: 12,
        padding: {
          page: 40,
          section: 12,
        },
        margins: {
          top: 40,
          bottom: 40,
          left: 40,
          right: 40,
        },
      },
      sections: [
        { id: 'summary', visible: true, order: 1, style: 'default' },
        { id: 'experience', visible: true, order: 2, style: 'default' },
        { id: 'education', visible: true, order: 3, style: 'default' },
        { id: 'skills', visible: true, order: 4, style: 'default' },
        { id: 'projects', visible: true, order: 5, style: 'default' },
        { id: 'certifications', visible: true, order: 6, style: 'default' },
      ],
    },
    tags: ['ATS-friendly', 'corporate', 'traditional'],
    isPremium: false,
    isATSFriendly: true,
    isOnePage: false,
    popularity: 95,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  
  {
    id: 'modern-minimal',
    name: 'Modern Minimal',
    description: 'Clean, lots of white space, perfect for tech roles',
    category: 'tech',
    style: 'modern',
    thumbnail: '/templates/thumbnails/modern-minimal.png',
    previewImages: ['/templates/previews/modern-minimal.png'],
    config: {
      layout: {
        type: 'single-column',
        headerStyle: 'left-aligned',
        columns: 1,
        showIcons: true,
        showDividers: false,
        compactMode: false,
      },
      typography: {
        fontFamily: 'inter',
        headingFont: 'inter',
        bodyFont: 'inter',
        sizes: {
          name: 28,
          heading: 16,
          subheading: 12,
          body: 10,
          small: 9,
        },
        weights: {
          normal: 400,
          medium: 500,
          semibold: 600,
          bold: 700,
        },
      },
      colors: colorSchemes.minimalBlack,
      spacing: {
        sectionGap: 24,
        itemGap: 16,
        padding: {
          page: 50,
          section: 8,
        },
        margins: {
          top: 50,
          bottom: 50,
          left: 50,
          right: 50,
        },
      },
      sections: [
        { id: 'summary', visible: true, order: 1, style: 'default' },
        { id: 'experience', visible: true, order: 2, style: 'default' },
        { id: 'skills', visible: true, order: 3, style: 'compact' },
        { id: 'education', visible: true, order: 4, style: 'compact' },
        { id: 'projects', visible: true, order: 5, style: 'default' },
      ],
    },
    tags: ['ATS-friendly', 'modern', 'minimal', 'tech'],
    isPremium: false,
    isATSFriendly: true,
    isOnePage: true,
    popularity: 88,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  
  {
    id: 'creative-bold',
    name: 'Creative Bold',
    description: 'Colorful and unique layout for creative professionals',
    category: 'creative',
    style: 'creative',
    thumbnail: '/templates/thumbnails/creative-bold.png',
    previewImages: ['/templates/previews/creative-bold.png'],
    config: {
      layout: {
        type: 'two-column',
        headerStyle: 'bold',
        columns: 2,
        showIcons: true,
        showDividers: false,
        compactMode: false,
      },
      typography: {
        fontFamily: 'montserrat',
        headingFont: 'montserrat',
        bodyFont: 'inter',
        sizes: {
          name: 32,
          heading: 16,
          subheading: 12,
          body: 10,
          small: 9,
        },
        weights: {
          normal: 400,
          medium: 500,
          semibold: 600,
          bold: 800,
        },
      },
      colors: colorSchemes.creativeOrange,
      spacing: {
        sectionGap: 20,
        itemGap: 14,
        padding: {
          page: 35,
          section: 10,
        },
        margins: {
          top: 35,
          bottom: 35,
          left: 35,
          right: 35,
        },
      },
      sections: [
        { id: 'summary', visible: true, order: 1, style: 'card' },
        { id: 'experience', visible: true, order: 2, style: 'timeline' },
        { id: 'skills', visible: true, order: 3, style: 'default' },
        { id: 'education', visible: true, order: 4, style: 'default' },
        { id: 'projects', visible: true, order: 5, style: 'card' },
      ],
    },
    tags: ['creative', 'colorful', 'two-column', 'design'],
    isPremium: true,
    isATSFriendly: false,
    isOnePage: false,
    popularity: 72,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  
  {
    id: 'academic-detailed',
    name: 'Academic Detailed',
    description: 'Comprehensive layout for academic and research positions',
    category: 'academic',
    style: 'classic',
    thumbnail: '/templates/thumbnails/academic-detailed.png',
    previewImages: ['/templates/previews/academic-detailed.png'],
    config: {
      layout: {
        type: 'single-column',
        headerStyle: 'centered',
        columns: 1,
        showIcons: false,
        showDividers: true,
        compactMode: true,
      },
      typography: {
        fontFamily: 'times',
        headingFont: 'times',
        bodyFont: 'times',
        sizes: {
          name: 22,
          heading: 13,
          subheading: 11,
          body: 10,
          small: 9,
        },
        weights: {
          normal: 400,
          medium: 500,
          semibold: 600,
          bold: 700,
        },
      },
      colors: colorSchemes.corporateGray,
      spacing: {
        sectionGap: 12,
        itemGap: 8,
        padding: {
          page: 30,
          section: 8,
        },
        margins: {
          top: 30,
          bottom: 30,
          left: 30,
          right: 30,
        },
      },
      sections: [
        { id: 'summary', visible: true, order: 1, style: 'compact' },
        { id: 'education', visible: true, order: 2, style: 'default' },
        { id: 'experience', visible: true, order: 3, style: 'default' },
        { id: 'publications', visible: true, order: 4, style: 'default' },
        { id: 'certifications', visible: true, order: 5, style: 'compact' },
        { id: 'skills', visible: true, order: 6, style: 'compact' },
      ],
    },
    tags: ['ATS-friendly', 'academic', 'research', 'detailed', 'multi-page'],
    isPremium: false,
    isATSFriendly: true,
    isOnePage: false,
    popularity: 65,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  
  {
    id: 'compact-single',
    name: 'Compact Single Page',
    description: 'Maximum information in minimum space',
    category: 'business',
    style: 'minimal',
    thumbnail: '/templates/thumbnails/compact-single.png',
    previewImages: ['/templates/previews/compact-single.png'],
    config: {
      layout: {
        type: 'two-column',
        headerStyle: 'minimal',
        columns: 2,
        showIcons: false,
        showDividers: false,
        compactMode: true,
      },
      typography: {
        fontFamily: 'arial',
        headingFont: 'arial',
        bodyFont: 'arial',
        sizes: {
          name: 20,
          heading: 12,
          subheading: 10,
          body: 9,
          small: 8,
        },
        weights: {
          normal: 400,
          medium: 500,
          semibold: 600,
          bold: 700,
        },
      },
      colors: colorSchemes.coolBlueGray,
      spacing: {
        sectionGap: 10,
        itemGap: 6,
        padding: {
          page: 25,
          section: 6,
        },
        margins: {
          top: 25,
          bottom: 25,
          left: 25,
          right: 25,
        },
      },
      sections: [
        { id: 'summary', visible: true, order: 1, style: 'compact' },
        { id: 'experience', visible: true, order: 2, style: 'compact' },
        { id: 'education', visible: true, order: 3, style: 'compact' },
        { id: 'skills', visible: true, order: 4, style: 'compact' },
        { id: 'certifications', visible: true, order: 5, style: 'compact' },
      ],
    },
    tags: ['ATS-friendly', 'one-page', 'compact', 'efficient'],
    isPremium: false,
    isATSFriendly: true,
    isOnePage: true,
    popularity: 80,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];