// lib/templates/baseTemplates.ts

import { Template } from "@/lib/types/template";
import { colorSchemes } from "./colorSchemes";

export const baseTemplates: Template[] = [
  // 1. Classic ATS-Friendly
  {
    id: 'classic-ats',
    name: 'Classic ATS-Friendly',
    description: 'Traditional single-column layout optimized for ATS systems. Perfect for corporate and traditional industries.',
    category: 'business',
    style: 'professional',
    thumbnail: '/templates/thumbnails/classic-ats.png',
    previewImages: [],
    config: {
      layout: {
        type: 'single-column',
        headerStyle: 'centered',
        columns: 1,
        showIcons: false,
        showDividers: true,
        compactMode: false,
      },
      typography: {
        fontFamily: 'arial',
        headingFont: 'arial',
        bodyFont: 'georgia',
        sizes: {
          name: 24,
          heading: 12,
          subheading: 11,
          body: 10,
          small: 9,
        },
        weights: {
          normal: 400,
          medium: 500,
          semibold: 600,
          bold: 700,
        },
      },
      colors: colorSchemes.professionalBlue,
      spacing: {
        sectionGap: 14,
        itemGap: 10,
        padding: {
          page: 40,
          section: 10,
        },
        margins: {
          top: 40,
          bottom: 40,
          left: 50,
          right: 50,
        },
      },
      sections: [
        { id: 'summary', visible: true, order: 1 },
        { id: 'experience', visible: true, order: 2 },
        { id: 'education', visible: true, order: 3 },
        { id: 'skills', visible: true, order: 4 },
      ],
    },
    tags: ['ATS-friendly', 'traditional', 'corporate', 'single-column'],
    isPremium: false,
    isATSFriendly: true,
    isOnePage: false,
    popularity: 95,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 2. Modern Two-Column
  {
    id: 'modern-two-column',
    name: 'Modern Two-Column',
    description: 'Clean two-column layout with sidebar. Perfect for tech and modern companies.',
    category: 'tech',
    style: 'modern',
    thumbnail: '/templates/thumbnails/modern-two-column.png',
    previewImages: [],
    config: {
      layout: {
        type: 'two-column',
        headerStyle: 'left-aligned',
        columns: 2,
        showIcons: true,
        showDividers: false,
        compactMode: false,
      },
      typography: {
        fontFamily: 'inter',
        headingFont: 'inter',
        bodyFont: 'inter',
        sizes: {
          name: 26,
          heading: 11,
          subheading: 10,
          body: 9,
          small: 8,
        },
        weights: {
          normal: 400,
          medium: 500,
          semibold: 600,
          bold: 700,
        },
      },
      colors: colorSchemes.modernTeal,
      spacing: {
        sectionGap: 16,
        itemGap: 10,
        padding: {
          page: 35,
          section: 8,
        },
        margins: {
          top: 35,
          bottom: 35,
          left: 35,
          right: 35,
        },
      },
      sections: [
        { id: 'summary', visible: true, order: 1 },
        { id: 'experience', visible: true, order: 2 },
        { id: 'education', visible: true, order: 3 },
        { id: 'skills', visible: true, order: 4 },
      ],
    },
    tags: ['modern', 'two-column', 'tech', 'clean'],
    isPremium: false,
    isATSFriendly: false,
    isOnePage: false,
    popularity: 92,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 3. Bold Creative Header
  {
    id: 'bold-creative-header',
    name: 'Bold Creative Header',
    description: 'Eye-catching colored header with clean body. Perfect for marketing and creative roles.',
    category: 'creative',
    style: 'creative',
    thumbnail: '/templates/thumbnails/bold-creative.png',
    previewImages: [],
    config: {
      layout: {
        type: 'single-column',
        headerStyle: 'bold',
        columns: 1,
        showIcons: false,
        showDividers: false,
        compactMode: false,
      },
      typography: {
        fontFamily: 'montserrat',
        headingFont: 'montserrat',
        bodyFont: 'roboto',
        sizes: {
          name: 28,
          heading: 12,
          subheading: 10,
          body: 9,
          small: 8,
        },
        weights: {
          normal: 400,
          medium: 500,
          semibold: 600,
          bold: 800,
        },
      },
      colors: colorSchemes.professionalBlue,
      spacing: {
        sectionGap: 16,
        itemGap: 10,
        padding: {
          page: 40,
          section: 8,
        },
        margins: {
          top: 0,
          bottom: 40,
          left: 40,
          right: 40,
        },
      },
      sections: [
        { id: 'summary', visible: true, order: 1 },
        { id: 'experience', visible: true, order: 2 },
        { id: 'education', visible: true, order: 3 },
        { id: 'skills', visible: true, order: 4 },
      ],
    },
    tags: ['creative', 'bold', 'marketing', 'design'],
    isPremium: false,
    isATSFriendly: false,
    isOnePage: false,
    popularity: 88,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 4. Minimalist Executive
  {
    id: 'minimalist-executive',
    name: 'Minimalist Executive',
    description: 'Elegant layout with generous white space. Perfect for senior positions and executives.',
    category: 'business',
    style: 'minimal',
    thumbnail: '/templates/thumbnails/minimalist-executive.png',
    previewImages: [],
    config: {
      layout: {
        type: 'single-column',
        headerStyle: 'centered',
        columns: 1,
        showIcons: false,
        showDividers: false,
        compactMode: false,
      },
      typography: {
        fontFamily: 'georgia',
        headingFont: 'georgia',
        bodyFont: 'georgia',
        sizes: {
          name: 28,
          heading: 11,
          subheading: 10,
          body: 10,
          small: 9,
        },
        weights: {
          normal: 400,
          medium: 500,
          semibold: 600,
          bold: 700,
        },
      },
      colors: colorSchemes.classicBlack,
      spacing: {
        sectionGap: 20,
        itemGap: 14,
        padding: {
          page: 50,
          section: 10,
        },
        margins: {
          top: 60,
          bottom: 50,
          left: 60,
          right: 60,
        },
      },
      sections: [
        { id: 'summary', visible: true, order: 1 },
        { id: 'experience', visible: true, order: 2 },
        { id: 'education', visible: true, order: 3 },
        { id: 'skills', visible: true, order: 4 },
      ],
    },
    tags: ['minimal', 'executive', 'elegant', 'senior'],
    isPremium: false,
    isATSFriendly: true,
    isOnePage: false,
    popularity: 85,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 5. Timeline Modern
  {
    id: 'timeline-modern',
    name: 'Timeline Modern',
    description: 'Experience displayed as visual timeline. Perfect for chronological careers.',
    category: 'tech',
    style: 'modern',
    thumbnail: '/templates/thumbnails/timeline-modern.png',
    previewImages: [],
    config: {
      layout: {
        type: 'timeline',
        headerStyle: 'left-aligned',
        columns: 1,
        showIcons: true,
        showDividers: false,
        compactMode: false,
      },
      typography: {
        fontFamily: 'inter',
        headingFont: 'inter',
        bodyFont: 'inter',
        sizes: {
          name: 26,
          heading: 12,
          subheading: 10,
          body: 9,
          small: 8,
        },
        weights: {
          normal: 400,
          medium: 500,
          semibold: 600,
          bold: 700,
        },
      },
      colors: colorSchemes.modernTeal,
      spacing: {
        sectionGap: 16,
        itemGap: 12,
        padding: {
          page: 40,
          section: 10,
        },
        margins: {
          top: 40,
          bottom: 40,
          left: 45,
          right: 45,
        },
      },
      sections: [
        { id: 'summary', visible: true, order: 1 },
        { id: 'experience', visible: true, order: 2 },
        { id: 'education', visible: true, order: 3 },
        { id: 'skills', visible: true, order: 4 },
      ],
    },
    tags: ['timeline', 'modern', 'visual', 'chronological'],
    isPremium: false,
    isATSFriendly: false,
    isOnePage: false,
    popularity: 80,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 6. Compact Professional
  {
    id: 'compact-professional',
    name: 'Compact Professional',
    description: 'Space-efficient layout that fits everything on one page. Perfect for entry-level.',
    category: 'business',
    style: 'professional',
    thumbnail: '/templates/thumbnails/compact-professional.png',
    previewImages: [],
    config: {
      layout: {
        type: 'single-column',
        headerStyle: 'minimal',
        columns: 1,
        showIcons: false,
        showDividers: true,
        compactMode: true,
      },
      typography: {
        fontFamily: 'arial',
        headingFont: 'arial',
        bodyFont: 'arial',
        sizes: {
          name: 20,
          heading: 11,
          subheading: 9,
          body: 9,
          small: 8,
        },
        weights: {
          normal: 400,
          medium: 500,
          semibold: 600,
          bold: 700,
        },
      },
      colors: colorSchemes.sophisticatedGray,
      spacing: {
        sectionGap: 10,
        itemGap: 8,
        padding: {
          page: 30,
          section: 6,
        },
        margins: {
          top: 30,
          bottom: 30,
          left: 35,
          right: 35,
        },
      },
      sections: [
        { id: 'summary', visible: true, order: 1 },
        { id: 'experience', visible: true, order: 2 },
        { id: 'education', visible: true, order: 3 },
        { id: 'skills', visible: true, order: 4 },
      ],
    },
    tags: ['compact', 'one-page', 'efficient', 'entry-level'],
    isPremium: false,
    isATSFriendly: true,
    isOnePage: true,
    popularity: 87,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 7. Tech/Startup Clean
  {
    id: 'tech-startup-clean',
    name: 'Tech/Startup Clean',
    description: 'Minimal sans-serif design with prominent links. Perfect for developers and startups.',
    category: 'tech',
    style: 'minimal',
    thumbnail: '/templates/thumbnails/tech-startup.png',
    previewImages: [],
    config: {
      layout: {
        type: 'single-column',
        headerStyle: 'left-aligned',
        columns: 1,
        showIcons: true,
        showDividers: false,
        compactMode: false,
      },
      typography: {
        fontFamily: 'roboto',
        headingFont: 'roboto',
        bodyFont: 'roboto',
        sizes: {
          name: 26,
          heading: 11,
          subheading: 10,
          body: 9,
          small: 8,
        },
        weights: {
          normal: 400,
          medium: 500,
          semibold: 600,
          bold: 700,
        },
      },
      colors: colorSchemes.classicBlack,
      spacing: {
        sectionGap: 16,
        itemGap: 10,
        padding: {
          page: 40,
          section: 8,
        },
        margins: {
          top: 40,
          bottom: 40,
          left: 45,
          right: 45,
        },
      },
      sections: [
        { id: 'summary', visible: true, order: 1 },
        { id: 'experience', visible: true, order: 2 },
        { id: 'skills', visible: true, order: 3 },
        { id: 'education', visible: true, order: 4 },
      ],
    },
    tags: ['tech', 'startup', 'developer', 'minimal', 'clean'],
    isPremium: false,
    isATSFriendly: true,
    isOnePage: false,
    popularity: 90,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 8. Executive Luxury
  {
    id: 'executive-luxury',
    name: 'Executive Luxury',
    description: 'Sophisticated dark-themed resume with gold accents. Perfect for C-level executives and senior management.',
    category: 'business',
    style: 'professional',
    thumbnail: '/templates/thumbnails/executive-luxury.png',
    previewImages: [],
    config: {
      layout: {
        type: 'single-column',
        headerStyle: 'centered',
        columns: 1,
        showIcons: false,
        showDividers: true,
        compactMode: false,
      },
      typography: {
        fontFamily: 'georgia',
        headingFont: 'georgia',
        bodyFont: 'georgia',
        sizes: {
          name: 32,
          heading: 13,
          subheading: 11,
          body: 10,
          small: 9,
        },
        weights: {
          normal: 400,
          medium: 500,
          semibold: 600,
          bold: 700,
        },
      },
      colors: {
        primary: '#D4AF37', // Gold
        secondary: '#1a1a1a',
        accent: '#B8860B',
        text: '#2c2c2c',
        textLight: '#5a5a5a',
        background: '#ffffff',
        border: '#D4AF37',
      },
      spacing: {
        sectionGap: 20,
        itemGap: 12,
        padding: {
          page: 50,
          section: 12,
        },
        margins: {
          top: 50,
          bottom: 50,
          left: 55,
          right: 55,
        },
      },
      sections: [
        { id: 'summary', visible: true, order: 1 },
        { id: 'experience', visible: true, order: 2 },
        { id: 'education', visible: true, order: 3 },
        { id: 'skills', visible: true, order: 4 },
      ],
    },
    tags: ['executive', 'luxury', 'premium', 'C-level'],
    isPremium: true,
    isATSFriendly: false,
    isOnePage: false,
    popularity: 94,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 9. Creative Portfolio
  {
    id: 'creative-portfolio',
    name: 'Creative Portfolio',
    description: 'Vibrant multi-color design with creative sections. Perfect for designers, artists, and creative professionals.',
    category: 'creative',
    style: 'creative',
    thumbnail: '/templates/thumbnails/creative-portfolio.png',
    previewImages: [],
    config: {
      layout: {
        type: 'asymmetric',
        headerStyle: 'creative',
        columns: 1,
        showIcons: true,
        showDividers: false,
        compactMode: false,
      },
      typography: {
        fontFamily: 'poppins',
        headingFont: 'poppins',
        bodyFont: 'openSans',
        sizes: {
          name: 34,
          heading: 14,
          subheading: 11,
          body: 10,
          small: 9,
        },
        weights: {
          normal: 400,
          medium: 500,
          semibold: 600,
          bold: 800,
        },
      },
      colors: {
        primary: '#6C63FF',
        secondary: '#FF6B9D',
        accent: '#FFA500',
        text: '#2d3748',
        textLight: '#718096',
        background: '#ffffff',
        border: '#e2e8f0',
      },
      spacing: {
        sectionGap: 24,
        itemGap: 14,
        padding: {
          page: 45,
          section: 10,
        },
        margins: {
          top: 45,
          bottom: 45,
          left: 45,
          right: 45,
        },
      },
      sections: [
        { id: 'summary', visible: true, order: 1 },
        { id: 'experience', visible: true, order: 2 },
        { id: 'skills', visible: true, order: 3 },
        { id: 'education', visible: true, order: 4 },
      ],
    },
    tags: ['creative', 'colorful', 'designer', 'portfolio'],
    isPremium: true,
    isATSFriendly: false,
    isOnePage: false,
    popularity: 89,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 10. Tech Leader
  {
    id: 'tech-leader',
    name: 'Tech Leader',
    description: 'Modern tech-focused design with sidebar metrics. Perfect for engineering managers and tech leads.',
    category: 'tech',
    style: 'modern',
    thumbnail: '/templates/thumbnails/tech-leader.png',
    previewImages: [],
    config: {
      layout: {
        type: 'two-column',
        headerStyle: 'minimal',
        columns: 2,
        showIcons: true,
        showDividers: false,
        compactMode: false,
      },
      typography: {
        fontFamily: 'sourceCodePro',
        headingFont: 'roboto',
        bodyFont: 'roboto',
        sizes: {
          name: 28,
          heading: 12,
          subheading: 10,
          body: 9,
          small: 8,
        },
        weights: {
          normal: 400,
          medium: 500,
          semibold: 600,
          bold: 700,
        },
      },
      colors: {
        primary: '#0EA5E9',
        secondary: '#1e293b',
        accent: '#06b6d4',
        text: '#334155',
        textLight: '#64748b',
        background: '#ffffff',
        border: '#cbd5e1',
      },
      spacing: {
        sectionGap: 16,
        itemGap: 10,
        padding: {
          page: 35,
          section: 8,
        },
        margins: {
          top: 35,
          bottom: 35,
          left: 35,
          right: 35,
        },
      },
      sections: [
        { id: 'summary', visible: true, order: 1 },
        { id: 'experience', visible: true, order: 2 },
        { id: 'skills', visible: true, order: 3 },
        { id: 'education', visible: true, order: 4 },
      ],
    },
    tags: ['tech', 'engineering', 'manager', 'leadership'],
    isPremium: true,
    isATSFriendly: true,
    isOnePage: false,
    popularity: 93,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 11. Infographic Modern
  {
    id: 'infographic-modern',
    name: 'Infographic Modern',
    description: 'Data-driven design with visual progress bars and charts. Perfect for data analysts and visual communicators.',
    category: 'creative',
    style: 'modern',
    thumbnail: '/templates/thumbnails/infographic-modern.png',
    previewImages: [],
    config: {
      layout: {
        type: 'two-column',
        headerStyle: 'bold',
        columns: 2,
        showIcons: true,
        showDividers: false,
        compactMode: false,
      },
      typography: {
        fontFamily: 'nunito',
        headingFont: 'nunito',
        bodyFont: 'nunito',
        sizes: {
          name: 30,
          heading: 13,
          subheading: 11,
          body: 10,
          small: 9,
        },
        weights: {
          normal: 400,
          medium: 600,
          semibold: 700,
          bold: 800,
        },
      },
      colors: {
        primary: '#10B981',
        secondary: '#3B82F6',
        accent: '#F59E0B',
        text: '#111827',
        textLight: '#6B7280',
        background: '#ffffff',
        border: '#D1D5DB',
      },
      spacing: {
        sectionGap: 18,
        itemGap: 11,
        padding: {
          page: 40,
          section: 10,
        },
        margins: {
          top: 40,
          bottom: 40,
          left: 40,
          right: 40,
        },
      },
      sections: [
        { id: 'summary', visible: true, order: 1 },
        { id: 'experience', visible: true, order: 2 },
        { id: 'skills', visible: true, order: 3 },
        { id: 'education', visible: true, order: 4 },
      ],
    },
    tags: ['infographic', 'visual', 'data', 'modern'],
    isPremium: true,
    isATSFriendly: false,
    isOnePage: false,
    popularity: 86,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 12. Elegant Professional
  {
    id: 'elegant-professional',
    name: 'Elegant Professional',
    description: 'Refined serif design with subtle colors. Perfect for consultants, lawyers, and finance professionals.',
    category: 'business',
    style: 'professional',
    thumbnail: '/templates/thumbnails/elegant-professional.png',
    previewImages: [],
    config: {
      layout: {
        type: 'single-column',
        headerStyle: 'centered',
        columns: 1,
        showIcons: false,
        showDividers: true,
        compactMode: false,
      },
      typography: {
        fontFamily: 'merriweather',
        headingFont: 'playfair',
        bodyFont: 'lora',
        sizes: {
          name: 30,
          heading: 13,
          subheading: 11,
          body: 10,
          small: 9,
        },
        weights: {
          normal: 400,
          medium: 500,
          semibold: 600,
          bold: 700,
        },
      },
      colors: {
        primary: '#4A5568',
        secondary: '#2D3748',
        accent: '#718096',
        text: '#1A202C',
        textLight: '#4A5568',
        background: '#ffffff',
        border: '#CBD5E0',
      },
      spacing: {
        sectionGap: 22,
        itemGap: 13,
        padding: {
          page: 50,
          section: 10,
        },
        margins: {
          top: 55,
          bottom: 50,
          left: 55,
          right: 55,
        },
      },
      sections: [
        { id: 'summary', visible: true, order: 1 },
        { id: 'experience', visible: true, order: 2 },
        { id: 'education', visible: true, order: 3 },
        { id: 'skills', visible: true, order: 4 },
      ],
    },
    tags: ['elegant', 'professional', 'serif', 'refined'],
    isPremium: true,
    isATSFriendly: true,
    isOnePage: false,
    popularity: 91,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 13. Modern Minimalist Pro
  {
    id: 'modern-minimalist-pro',
    name: 'Modern Minimalist Pro',
    description: 'Ultra-clean design with strategic use of negative space. Perfect for modern professionals in any field.',
    category: 'tech',
    style: 'minimal',
    thumbnail: '/templates/thumbnails/modern-minimalist-pro.png',
    previewImages: [],
    config: {
      layout: {
        type: 'single-column',
        headerStyle: 'left-aligned',
        columns: 1,
        showIcons: false,
        showDividers: false,
        compactMode: false,
      },
      typography: {
        fontFamily: 'inter',
        headingFont: 'inter',
        bodyFont: 'inter',
        sizes: {
          name: 36,
          heading: 14,
          subheading: 11,
          body: 10,
          small: 9,
        },
        weights: {
          normal: 300,
          medium: 400,
          semibold: 600,
          bold: 700,
        },
      },
      colors: {
        primary: '#000000',
        secondary: '#404040',
        accent: '#808080',
        text: '#262626',
        textLight: '#737373',
        background: '#ffffff',
        border: '#e5e5e5',
      },
      spacing: {
        sectionGap: 28,
        itemGap: 16,
        padding: {
          page: 50,
          section: 10,
        },
        margins: {
          top: 60,
          bottom: 60,
          left: 60,
          right: 60,
        },
      },
      sections: [
        { id: 'summary', visible: true, order: 1 },
        { id: 'experience', visible: true, order: 2 },
        { id: 'education', visible: true, order: 3 },
        { id: 'skills', visible: true, order: 4 },
      ],
    },
    tags: ['minimal', 'modern', 'clean', 'versatile'],
    isPremium: true,
    isATSFriendly: true,
    isOnePage: false,
    popularity: 95,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 14. Dynamic Gradient
  {
    id: 'dynamic-gradient',
    name: 'Dynamic Gradient',
    description: 'Eye-catching gradient header with modern styling. Perfect for marketing, sales, and growth professionals.',
    category: 'creative',
    style: 'modern',
    thumbnail: '/templates/thumbnails/dynamic-gradient.png',
    previewImages: [],
    config: {
      layout: {
        type: 'single-column',
        headerStyle: 'gradient',
        columns: 1,
        showIcons: true,
        showDividers: false,
        compactMode: false,
      },
      typography: {
        fontFamily: 'raleway',
        headingFont: 'raleway',
        bodyFont: 'openSans',
        sizes: {
          name: 32,
          heading: 13,
          subheading: 11,
          body: 10,
          small: 9,
        },
        weights: {
          normal: 400,
          medium: 500,
          semibold: 600,
          bold: 800,
        },
      },
      colors: {
        primary: '#8B5CF6',
        secondary: '#EC4899',
        accent: '#F59E0B',
        text: '#1F2937',
        textLight: '#6B7280',
        background: '#ffffff',
        border: '#E5E7EB',
      },
      spacing: {
        sectionGap: 20,
        itemGap: 12,
        padding: {
          page: 45,
          section: 10,
        },
        margins: {
          top: 0,
          bottom: 45,
          left: 45,
          right: 45,
        },
      },
      sections: [
        { id: 'summary', visible: true, order: 1 },
        { id: 'experience', visible: true, order: 2 },
        { id: 'skills', visible: true, order: 3 },
        { id: 'education', visible: true, order: 4 },
      ],
    },
    tags: ['gradient', 'modern', 'marketing', 'vibrant'],
    isPremium: true,
    isATSFriendly: false,
    isOnePage: false,
    popularity: 88,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 15. Academic Scholar
  {
    id: 'academic-scholar',
    name: 'Academic Scholar',
    description: 'Traditional academic format with publication-friendly layout. Perfect for academics, researchers, and PhDs.',
    category: 'business',
    style: 'professional',
    thumbnail: '/templates/thumbnails/academic-scholar.png',
    previewImages: [],
    config: {
      layout: {
        type: 'single-column',
        headerStyle: 'centered',
        columns: 1,
        showIcons: false,
        showDividers: true,
        compactMode: false,
      },
      typography: {
        fontFamily: 'timesNewRoman',
        headingFont: 'timesNewRoman',
        bodyFont: 'timesNewRoman',
        sizes: {
          name: 24,
          heading: 12,
          subheading: 11,
          body: 11,
          small: 10,
        },
        weights: {
          normal: 400,
          medium: 500,
          semibold: 600,
          bold: 700,
        },
      },
      colors: {
        primary: '#1a1a1a',
        secondary: '#2d2d2d',
        accent: '#4d4d4d',
        text: '#000000',
        textLight: '#404040',
        background: '#ffffff',
        border: '#000000',
      },
      spacing: {
        sectionGap: 16,
        itemGap: 10,
        padding: {
          page: 50,
          section: 8,
        },
        margins: {
          top: 50,
          bottom: 50,
          left: 60,
          right: 60,
        },
      },
      sections: [
        { id: 'summary', visible: true, order: 1 },
        { id: 'education', visible: true, order: 2 },
        { id: 'experience', visible: true, order: 3 },
        { id: 'skills', visible: true, order: 4 },
      ],
    },
    tags: ['academic', 'research', 'traditional', 'scholarly'],
    isPremium: true,
    isATSFriendly: true,
    isOnePage: false,
    popularity: 82,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];